### ISSUE TITLE
Helpers dont make hot change

### ISSUE THREAD

**Issue by ozluy** [artisavotins/react-redux-i18n#16]
`var I18n = require('react-redux-i18n').I18n;`

I used this helper and when I change language it does not change language of another component's content until another event triggers (does not make hot change.

If you tell me how I can get text instead of span element inside the `Translate` component I will get over my problem. 
Thanks.

**Comment by tiaaaa123** [comment]
I'm having the same kind of issue. Whatever the local is in the reducer, it keeps the language to english (probably my chrome locale.
Using setLocal does change the locale in the reducer, but it does't change the text (even when reloading the page)

`configureStore.js`
```
import { createStore, applyMiddleware, compose } from 'redux';
import thunk from 'redux-thunk';
import { loadTranslations, setLocale, syncTranslationWithStore, } from 'react-redux-i18n';
import reducer from '../reducers';
import translations from '../i18n';

export default function configureStore() {
  const enhancer = compose(
        applyMiddleware(thunk),
    );

  const store = createStore(
        reducer,
        enhancer,
    );

  if (module.hot) {
    module.hot.accept(() => {
      const nextRootReducer = reducer;
      store.replaceReducer(nextRootReducer);
    });
  }

  syncTranslationWithStore(store);
  store.dispatch(loadTranslations(translations));
  store.dispatch(setLocale('fr'));

  return store;
}
```

`reducers/index.js`
```
import { combineReducers } from 'redux';
import { i18nReducer } from 'react-redux-i18n';
...

const rootReducer = combineReducers({
  ... //other reducer
  i18n: i18nReducer,
});

export default rootReducer;
```

`component`
```
import { I18n } from 'react-redux-i18n';
...
<span>{I18n.t('modifyMyProfile')}</span>
```

Any Idea why it doesn't take the i18n local value?

**Comment by ozluy** [comment]
Hi @tiaaaa123,
If you are using ES6 did you try Translate object or you want to bind only text?

**Comment by ozluy** [comment]
if you want to set  only text 
you can use  redux as below,

__i18n__
_fr.js_
```
{
  app: {
    modifyMyProfile: 'Something in French'
  }
}
```
_en.js_
```
{
  app: {
    modifyMyProfile: 'Modify My Profile '
  }
}
```

_index.js_
```
import { fr } from './tr';
import { en } from './en';
export const translations = {
    fr: fr,
    en: en
};
```
__component__
```javascript
...
<span>{this.props.i18n.translations[this.props.i18n.locale].app.modifyMyProfile}</span>

...
const mapStateToProps = (state) => {
    return { 
        i18n: state.i18n
    };
};
export default connect(mapStateToProps, null)(Component);
```

**Comment by tiaaaa123** [comment]
It works, thank!
Although I was hoping to be able to do like `react-native-i18n` which is similar, plus simplier

```
import I18n from 'react-native-i18n'

class Demo extends React.Component {
  render () {
    return (
      <Text>{I18n.t('greeting')}</Text>
    )
  }
}

// Enable fallbacks if you want `en-US` and `en-GB` to fallback to `en`
I18n.fallbacks = true

I18n.translations = {
  en: {
    greeting: 'Hi!'
  },
  fr: {
    greeting: 'Bonjour!'
  }
}
```

No need to store anything in the reducer or else where. It just... works. Couldn't found one like it for Web.

P.S. I had to change your way to get the value to this
`i18n.translations.schedule[i18n.locale].modifyMyProfile.toUpperCase()`
where `i18n = this.props.i18n`
all the translation wont be in the same file, but all file will have 2 languages (instead of dividing it in 2 files) So In transaction, I choose the file (schedule in my exemple) then the language.

Here's my schedule translation file :
```
const translations = {
  en: {
    modifyMyProfile: 'Modify my profile',
  },
  fr: {
    modifyMyProfile: 'Modifier mon profil',
  }
};

export default translations;
```
And my main I18n folder: 
```
import schedule from '../../schedule/i18n';

const translations = {
  schedule,
};

export default translations;
```

**Comment by tiaaaa123** [comment]
@ozluy 
After looking at it, I don't really want to use this technic, because it means I have to connect every component with text to Redux.... Which is bad in my opinion, because some of them shouldn't need to know about the store... Which is why i wanted to use I18n.t(...)

**Comment by ozluy** [comment]
yeah @tiaaaa123,
I just tried to help you figure out but I opened that issue before but no response from owners...
