### ISSUE TITLE
how can be refreshed strings generated from I18n.t helper

### ISSUE THREAD

**Issue by SelenaRosso** [artisavotins/react-redux-i18n#17]
Hi,

In our web application based on Redux and React, we have a drop down to change dynamically of language. <Translate > component refresh workd fine. But as you mentionned in the readme file, I18n.t helper refresh is up to us. 
Actually, we use this helpers for tooltips like this : 

< li title={I18n.t("application.tooltip.displayRecent")}> 
     < Translate value="application.navigation.navRecent"/>
< /li>

How can we handle the refresh for helpers ?

Thanks

**Comment by ozluy** [comment]
hi @SelenaRosso 
check whether its helpful my Redux solution on issue #16
