### ISSUE TITLE
re-render on setLocale()

### ISSUE THREAD

**Issue by tiaaaa123** [artisavotins/react-redux-i18n#24]
Hi, 
I'm using the I18n.t helper and when I make a `dispatch(setLocale('fr'))` it does change the I18n language, but it doesn't re-render all the text using it.
Anyone got an Idea how to make it work?

**Comment by jalkoby** [comment]
force react re-render

**Comment by webwelten** [comment]
Can you specify further how you're architecture looks like and how it changes the I18n language but doesn't re-render the texts? In my case (just tried) it works. So let's try to find out where there are differences.
