### ISSUE TITLE
fix for react/redux app with Immutable js

### ISSUE THREAD

**Issue by Marshevskyy** [artisavotins/react-redux-i18n#26]
hey! for some reason I can not create PR.

please verify and add update code when you get a chance:

in method "`syncTranslationWithStore`" replace 

`store.getState().i18n`
to 

> store.getState().i18n ? store.getState().i18n.translations : store.getState().toJS().i18n.translations;

**Comment by mysticx** [comment]
I am just looking into this issue as well. I want to use both redux-immutable and read-redux-i18n, but can't seem to find a way around.
