### ISSUE TITLE
update rreact-i18nify to 1.8.7

### ISSUE THREAD

**Issue by dima-bu** [artisavotins/react-redux-i18n#28]
Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead.

**Comment by rotem925** [comment]
Any update on this one? That needed in order to eliminate the warning of prop-types packages (deprecated React.PropTypes)

**Comment by cinic** [comment]
When?

**Comment by EvgeniyPolovniy** [comment]
Any update?

**Comment by webbushka** [comment]
Seems like this was fixed in #37

**Comment by flo-sch** [comment]
`1.9.2` version just released, with`"react-i18nify": "^1.11.8"`, thanks to @artisavotins 

This can be closed I guess?

**Comment by artisavotins** [comment]
Closing it
