### ISSUE TITLE
Uncaught TypeError: Cannot read property 'options' of undefined at new Translate (translate.js:63)

### ISSUE THREAD

**Issue by tabletfrontend** [artisavotins/react-redux-i18n#31]
I am not sure why this error is happening. Looks like something to do with the configuration of i18n. 

The line at translate.js:63 is:

`namespaces = namespaces || _this.i18n.options.defaultNS;`

Where do the i18n options get configured? Am I configuring something wrong with my reducer?

**Comment by tabletfrontend** [comment]
Although, I think this might be an issue with react-i18nify

**Comment by admangum** [comment]
Is your component wrapped in a <I18nextProvider />?

**Comment by dvcarter** [comment]
I had similar problem. I solved it by importing i18n in my root rending file ( found at ../src/index.js) if you're borrowing from the create-react-app boilerplate. That is, I added `import './i18n'`to index.js.

**Comment by flo-sch** [comment]
Problem of `react-i18nify` package itself apparently.

Can any of you please test if this has been solved by `1.9.2` release?

**Comment by AKFourSeven** [comment]
I can confirm that I can still have this issue, is there a workaround or this ?

**Comment by artisavotins** [comment]
Sorry, but I don't see the use of `react-redux-i18n` in your example, @AKFourSeven 

Are you sure it is related to this package?

**Comment by AKFourSeven** [comment]
Sorry did not realize it was not a react-i18next issue? I will report to them instead.

**Comment by BaggioWongHK** [comment]
What did it for me was exactly what @admangum suggested, literally wrap your component like so

```
<I18nextProvider i18n={i18n}>
          // your component
</I18nextProvider>
```

where `i18n` would be your `i18nConfig`. Not sure how helpful this is, but just wanted to add a comment in case it is to someone.
