### ISSUE TITLE
Looking for new maintainers

### ISSUE THREAD

**Issue by operatino** [artisavotins/react-redux-i18n#35]
As we don't use the library day to day anymore, unfortunately we can't meet the proper maintenance requirements. To keep the project rolling, we're looking for a new maintainer (and owner).

If you're interested in taking over the project, please reach me by r@rhr.me or original project author - Gerben gerben.meyer@gmail.com

**Comment by artisavotins** [comment]
I'm the new maintainer. Feel free to address me if such a need arises!
