### ISSUE TITLE
Translating a group of Objects/Strings

### ISSUE THREAD

**Issue by dbrrt** [artisavotins/react-redux-i18n#36]
Is that possible to translate on the fly a group of strings, for instance, assuming a list of fruits : 
['banana', 'apple', 'apricot', 'pineapple'] to the equivalent list in another language ?
A specific use case, would be Dropdown lists, for which rendering is updated if the user selects another language.

**Comment by dbrrt** [comment]
It's possible to solve this quite simply : 

``` JavaScript
     import { Translate } from 'react-redux-i18n'

      const options =
       [
         { key: 'apple', text: <Translate value='fruit.apple' />, value: 'apple' },
         { key: 'pineapple', text: <Translate value='fruit.pineapple' />, value: 'pineapple' }
       ]

     <Dropdown  fluid search selection options={options}   />

```
I assume it's an efficient way to do this.

**Comment by artisavotins** [comment]
Why not use `I18n.t` function for this task? `Translate` returns a string wrapped in a DOM element, which can lead to unwanted side effects.

**Comment by dbrrt** [comment]
Good point, I've used later `I18n` to translate placeholders rather than `Translate` (works in this case, but not optimal)
