### ISSUE TITLE
Not possible to add html link element as prop!

### ISSUE THREAD

**Issue by lazaki** [artisavotins/react-redux-i18n#39]
` <Translate var={<a href="/aaa/a"}>LINK</a>} value={`dynamicKey${index}`} />`

**Comment by flo-sch** [comment]
This feature has been added to version `1.10.2` of `react-i18nify` and it should be possible to do such things very soon, once the dependency will be merged :)

https://github.com/JSxMachina/react-i18nify/pull/40

**Comment by artisavotins** [comment]
`react-i18nify` dependency has now been updated to `1.11.8`. Corresponding npm version is `1.9.2`. Since it re-exports `Translate` and `I18n` from `reat-i18nify`, you should be able to use all the latest features.
