### ISSUE TITLE
react-i18nify needs a patch to allow for multiple calls to `t()`

### ISSUE THREAD

**Issue by shanimal** [artisavotins/react-redux-i18n#40]
react-i18nify needs a patch to prevent overwriting dynamic placeholders
```
en : {
  really: {
    deeply: {
      nested: {
        name1: 'You are %{age} years old',
      },
    }
  }
}

t('really.deeply.nested', { age: 30 }).name1 // You are 30 years old
t('really.deeply.nested', { age: 20 }).name1 // You are 30 years old
```
expected `// You are 20 years old`

https://github.com/JSxMachina/react-i18nify/issues/38

**Comment by shanimal** [comment]
This issue [was resolved in react-i18nify](https://github.com/JSxMachina/react-i18nify/commit/dc16ab93d17f7d64186d678bb49a1224e17190e0) so we just need to update to the latest. Cheers!

**Comment by artisavotins** [comment]
`react-i18nify` dependency has now been updated to `1.11.8`. Corresponding npm version is `1.9.2`. Since it re-exports `Translate` and `I18n` from `reat-i18nify`, you should be able to use all the latest features.
