### ISSUE TITLE
react-i18nify update

### ISSUE THREAD

**Issue by AlexMarvelo** [artisavotins/react-redux-i18n#41]
It's recommended to update `react-i18nify` dependency to `1.9.1`, where `react` dependency was added to peerDependencies. It will avoid duplications of react lib in my project, since we use `react@^16`

**Comment by flo-sch** [comment]
I would actually love to have it updated to `1.10.0`, in order to benefit from the new `tag` prop, allowing to choose an HTML element to render the translation :)

`<Translate tag='div' value='...' />`

**Comment by artisavotins** [comment]
`react-i18nify` dependency has now been updated to `1.11.8`
