### ISSUE TITLE
LTS key for localization does not work as expected

### ISSUE THREAD

**Issue by eakarpov** [artisavotins/react-redux-i18n#42]
Using ```<Localize value={value} dateFormat="LTS" />``` does not return 01.01.2018 12:16:20 PM as expected from moment.js documentation.
It returns 01.01.2018t20 (as using L and S key separately with t as string constant).

**Comment by flo-sch** [comment]
Isn't this issue related to https://github.com/JSxMachina/react-i18nify instead ?

**Comment by eakarpov** [comment]
@flo-sch maybe. I will write the issue there.

**Comment by eakarpov** [comment]
@flo-sch react-i18nify fixed that in 1.11.9 version. Please update the dependency.

**Comment by flo-sch** [comment]
I created a PR for that but I'm not really a dedicated developer of this package, you could have done it as well :)

**Comment by eakarpov** [comment]
OK, thanks!
