### ISSUE TITLE
Using multiple files

### ISSUE THREAD

**Issue by robertomellocampos** [artisavotins/react-redux-i18n#46]
Can I separate my translation files by language and start the component through this folder setting the locale? For example: file.pt-BR.json, file.en-US.json...

Best Regards,

**Comment by Saifadin** [comment]
Sure its possible. We are separating our folder structure like this:

```
locale
|__ translations.js
|__ en
     |__ index.js
     |__ forms.js
|__ de
     |__ index.js
     |__ forms.js
```

_translations.js_
```javascript
import en from './en';
import de from './de';

export default {
  de,
  en
};
```

_en/index.js_
```javascript
import forms from './forms';

const localesEn = {
  language: 'en',
  forms
};

export default localesEn;
```

that way you can even split the files into parts of your application and bundle them by language first. With this structure you can just translate a whole language folder and just add it into the structure.

Hope it helps
